# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fbbfba9506ff7dad7860c7e49ecf5f98b25ef4330d4bff64127efc6d85ece97971e19e6050fc46e89bc1c4a2bac2198b9d02e8052b17d9b5862674bfe26da68

test:
  secret_key_base: 3b2bd7ff8af99deda9258c3edb3b2e02637ce00bbec0d2197efda039a5689827fa1cc60818a6ba651ed816fd833cc03787c527e4003badc0b8dcd8d5b51058bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
